# Generated by Django 5.0.1 on 2024-11-11 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='ConditionList',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doleance',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='EquipeFonction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='EquipeNom',
            field=models.CharField(max_length=100),
        ),
    ]
