# Generated by Django 5.0.1 on 2024-11-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0002_alter_condition_conditionlist_alter_doleance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='ConditionList',
            field=models.CharField(max_length=2000),
        ),
    ]
